config/routes.rb
GymTime::Application.routes.draw do
  resources :exercises
  resources :users, only:[:new, :create]
  resources :workouts
  resources :authenticates, only:[:new, :create]
  delete "authenticates" => "authenticates#destroy"
  resources :entries
  get '/map' => 'home#map'
  

   root 'home#index'

end

app/models/workout.rb
class Workout
  include Mongoid::Document

  belongs_to :user
  has_and_belongs_to_many :exercises
  
  field :body_part, type: String
  field :exercise, type: String
  field :workout_date, type: String

  validates :body_part, :presence => true
  validates :workout_date, :presence => true
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  def index
    # Make sure user is logged in (applies to other methods also)
    if current_user
      # @workouts = Workout.all
      # Only show assigned users workouts and order them by earliest date for json
      @workouts = current_user.workouts.order_by(:workout_date.asc)
      @time = Time.now.strftime("%Y-%m-%d")
    else
      redirect_to new_authenticate_path
      flash[:notice] = "Please log in first to see your workouts"
    end
  end

  def new
    if current_user
      @workout = Workout.new
    else
      redirect_to new_authenticate_path
      flash[:notice] = "Please log in before creating a workout"
    end
  end

  def show
    if current_user
      @workout = Workout.find(params[:id])
     else
      redirect_to new_authenticate_path
      flash[:notice] = "Please log in before viewing a workout"
    end
  end

  def edit
  	@workout = Workout.find(params[:id])
  end

  def create
  	@workout = Workout.new(workout_params)
    # Assign workout to current user
    @workout.user = current_user 
  	if @workout.save
  		flash[:notice] = "Successfully Created A Workout!"
  		redirect_to action: 'index'
  	else
  		render action: 'new'
  	end
  end

  def update
  	@workout = Workout.find(params[:id])
  	if @workout.update(workout_params)
  		flash[:notice] = "Successfully Updated Your Workout!"
  		redirect_to action: 'index'
  	else
  		render action: 'edit'
		end
	end

	def destroy
		@workout = Workout.find(params[:id])
		@workout.destroy
		flash[:notice] = "Successfully Deleted Your Workout!"
		redirect_to action: 'index'
	end

	private

	def workout_params
		params.require(:workout).permit(:body_part, :exercise, :workout_date, exercise_ids: [])	
	end
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/workouts/_form.html.erb
<%= form_for @workout do |f| %>
	<div>
		<%= f.label "Body Part(s)" %><br />
		<%= f.text_field :body_part, :required => true  %>
	</div>
	<br>
	<div>
			<%= f.label :workout_date%> <br />
			<%= f.text_field :workout_date, :class=>"datepicker", :required => true %>
	</div>
	<div class="exercises">
		<fieldset>
		  <p>Select Exercise(s):</p>
		  <!-- current_user should be added before exercises.all to grab only current users' exercises -->
		  <p class="options"><%= f.collection_check_boxes :exercise_ids, current_user.exercises.all, :id, :name %></p>
		</fieldset>
	</div>
	<div><%= f.submit :class=>"btn btn-success" %></div>
<% end %>

app/views/workouts/edit.html.erb
<div class="workout">
	<h2>Edit Workout</h2>
	<%= render partial: 'form' %>
	<span class="btn btn-danger" >
		<%= link_to "Delete Workout", @workout , {method: :delete, confirm: "Are You Sure You Want To Delete This Workout?"} %>
	</span>
	<span class="btn btn-default">
		<%= link_to "Go Back", workouts_path %>
	</span>
</div>

app/views/workouts/index.html.erb
<div id ="upcoming">
	<table>
		<tr>
			<th>Today's Workout</th>
		</tr>
		<tr>
			<td>				
				<% @workouts.each do |workout| %>
					<!-- Check first to make sure that loop doesnt pick up previous days -->
					<% if workout.workout_date >= @time %>
						<!-- Only show today's workout -->
						<% if workout.workout_date == @time%>
							<%= workout.workout_date %>
							<hr>
							<p>BODY PART(S):</p>
							<%= workout.body_part %>
							<hr>
							<p>EXERCISE(S):</p>
							<!-- Limit 3 exercises showing on table -->
							<% workout.exercises.take(3).each do |exercise|%>
								<p><%= exercise.name%></p>
							<% end %>
							<h6><%= link_to "(view all exercises for workout)", workout %></h6>
							<!-- Break loop as soon as workout found to prevent else statement showing -->
							<% break %>
						<% else %>
							<p><%= "No Workout Scheduled For Today." %></p>
							<p><%= "Rest Up And Get Ready For The Next One!" %></p>	
							<!-- Break loop if there is not workout today -->
							<% break %>
						<% end %>
					<% end %>
				<% end %>
			</td>
		</tr>
	</table>	
	<table id="recent">
		<tr>
			<th>Recent Journal Entries</th>
		</tr>
		<tr>
			<td>
				<!-- Limit 3 entries to show -->
				<% current_user.entries.take(3).each do |entry| %>
					<p>
						<%= link_to entry.title, entry %>
						<%= "(#{entry.entry_date})" %>
					</p>
				<% end %>
				<h6><%= link_to "(view all journal entries)", entries_path %></h6>
		</td>
		</tr>
	</table>
</div>

<!--Calendar ID calls the jquery calendar to render-->
<div id="calendar">
  <br>
  <%= link_to "Add New Workout", new_workout_path, :class=>"btn btn-primary btn-xs" %>&nbsp;
  <%= link_to "Add Journal Entry", new_entry_path, :class=> "btn btn-default btn-xs", :id=>"journal" %>
  <p class="notice"><%= flash[:notice] %></p>
</div> 

<!-- Calendar function with data/json source paths -->
<script> $(document).ready(function() {
    $('#calendar').fullCalendar({
      aspectRatio: 1.8,
      //index.jason.jbuilder file will parse json data
      eventSources: [
        {
            url: 'workouts.json', 
            color: '#000056', 
        },
        
        {
            url: 'entries.json', 
            color: '#4b4b4b', 
        }]
    })
});
</script>

app/views/workouts/new.html.erb
<div class="workout">
	<h2>Create New Workout</h2>
	<%= render partial: 'form' %>
	<p class="btn btn-default"><%= link_to "Go Back", workouts_path %></p>
</div>

app/views/workouts/show.html.erb
<div class="workout">
	<h3><%= @workout.body_part + " Workout" %></h3>
	<h4><%= "(#{@workout.workout_date})" %></h4>
	<hr>
	<% @workout.exercises.each do |exercise| %>
	<h4><%= link_to exercise.name, exercise %></h4>
	<% end %>
	<br><br>
	<div>
		<span class="btn btn-success"><%= link_to "Edit Workout", edit_workout_path%></span>
		<span class="btn btn-default"><%= link_to "Go Back", workouts_path%></span>
	</div>
</div>