config/routes.rb
GymTime::Application.routes.draw do
  resources :exercises
  resources :users, only:[:new, :create]
  resources :workouts
  resources :authenticates, only:[:new, :create]
  delete "authenticates" => "authenticates#destroy"
  resources :entries
  get '/map' => 'home#map'
  

   root 'home#index'

end

app/models/entry.rb
class Entry
  include Mongoid::Document

  belongs_to :user
  belongs_to :workout
  
  field :title, type: String
  field :entry_date, type: String
  field :content, type: String
  field :exercise, type: String
  field :exercise_two, type: String
  field :exercise_three, type: String
  field :sets, type: Integer
  field :sets_two, type: Integer
  field :sets_three, type: Integer
  field :reps, type: Integer
  field :reps_two, type: Integer
  field :reps_three, type: Integer
  field :lbs, type: String
  field :lbs_two, type: String
  field :lbs_three, type: String


  validates :title, :presence => true
  validates :entry_date, :presence => true
  validates :content, :presence => true
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  def index
    if current_user
      # @entries = Entry.all
      # Order earliest by earliest date
      @entries = current_user.entries.order_by(:entry_date.asc)
    else
      redirect_to new_authenticate_path
      flash[:notice] = "Please log in first to see your entries"
    end
  end

  def edit
  	@entry = Entry.find(params[:id])
  end

  def new
  	if current_user
      @entry = Entry.new
    else
      redirect_to new_authenticate_path
      flash[:notice] = "Please log in before creating a entry"
    end
  end

  def show
  	if current_user
      @entry = Entry.find(params[:id])
     else
      redirect_to new_authenticate_path
      flash[:notice] = "Please log in before viewing a entry"
    end
  end

  def create
  	@entry = Entry.new(entry_params)
    # Attach entry to current user 
    @entry.user = current_user 
  	if @entry.save
  		flash[:notice] = "Successfully Created An Entry!"
  		redirect_to action: 'index'
  	else
  		render action: 'new'
  	end
  end

  def update
  	@entry = Entry.find(params[:id])
  	if @entry.update(entry_params)
  		flash[:notice] = "Successfully Updated Your Entry!"
  		redirect_to action: 'index'
  	else
  		render action: 'edit'
		end
	end

	def destroy
		@entry = Entry.find(params[:id])
		@entry.destroy
		flash[:notice] = "Successfully Deleted Your Entry!"
		redirect_to action: 'index'
	end

  private

	def entry_params
		params.require(:entry).permit(:title, :entry_date, :content, :exercise, :exercise_two, :exercise_three, :reps, :reps_two, :reps_three, :sets, :sets_two, :sets_three, :lbs, :lbs_two, :lbs_three )	
	end
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/entries/_form.html.erb
<%= form_for @entry do |f| %>
	<div>
		<%= f.label :title %><br />
		<%= f.text_field :title, :required => true  %>
	</div>
	<br>
	<div>
		<%= f.label :"Date" %><br />
		<%= f.text_field :entry_date, :class=>"datepicker", :required => true  %>
	</div>
	<br>
	<div>
			<%= f.label "Entry"%> <br />
			<%= f.text_area :content, :required => true, :cols => "100", :rows => "5", :class=>"textbox" %>
	</div>
	<br>
	<div>
		<table>
			<th><%= f.label :exercise %></th>
			<th><%= f.label :sets %></th>
			<th><%= f.label :reps %></th>
			<th><%= f.label :lbs %></th>
			<tr>
				<td><%= f.text_field :exercise  %></td>
				<td><%= f.text_field :sets  %></td>
				<td><%= f.text_field :reps %></td>
				<td><%= f.text_field :lbs %></td>
			</tr>

			<th><%= f.label "Exercise" %></th>
			<th><%= f.label "Sets" %></th>
			<th><%= f.label "Reps" %></th>
			<th><%= f.label "LBS" %></th>
			<tr>
				<td><%= f.text_field :exercise_two  %></td>
				<td><%= f.text_field :sets_two  %></td>
				<td><%= f.text_field :reps_two %></td>
				<td><%= f.text_field :lbs_two %></td>
			</tr>

			<th><%= f.label "Exercise" %></th>
			<th><%= f.label "Sets"   %></th>
			<th><%= f.label "Reps" %></th>
			<th><%= f.label "LBS" %></th>
			<tr>
				<td><%= f.text_field :exercise_three  %></td>
				<td><%= f.text_field :sets_three   %></td>
				<td><%= f.text_field :reps_three  %></td>
				<td><%= f.text_field :lbs_three %></td>
			</tr>
		</table>
	</div>
	<br>
	<div><%= f.submit :class=>"btn btn-success" %></div>
<% end %>

app/views/entries/edit.html.erb
<div class="entry">
	<h2>Edit Entry</h2>
	<%= render partial: 'form' %>
	<span class="btn btn-danger">
		<%= link_to "Delete Entry", @entry, {method: :delete, confirm: "Are You Sure You Want To Delete This Entry?"} %>
	</span>
	<span class="btn btn-default">
		<%= link_to "Go Back", entries_path %>
	</span>
</div>

app/views/entries/index.html.erb
<div class="entry">
	<h3>Workout Journal</h3>
	<p class="notice"><%= flash[:notice] %></p>
	<div class="entries">
		<% @entries.each do |entry| %>
			<p>
				<%= link_to entry.title, entry %>
				<%= "(#{entry.entry_date})" %>
			</p>
		<% end %>
	</div>
  <p><%= link_to "Add New Journal Entry", new_entry_path, :class=>"btn btn-primary btn-xs", :id=>"journal" %></p>
  <p><%= link_to "Back to Workouts Calendar", workouts_path %></p>
</div>

app/views/entries/new.html.erb
<div class="entry">
	<h3>New Journal Entry</h3>
	<%= render partial: 'form' %>
	<p class="btn btn-default"><%= link_to "Go Back", entries_path %></p>
</div>

app/views/entries/show.html.erb
<div class="entry">
	<h2><%= @entry.title %></h2>
	<h5><%= "(#{@entry.entry_date})" %></h5>
	<hr>
	<h3>Journal Entry </h3>	
	<h5><%= @entry.content %></h5>
	<hr>
	<h3>Workout Log</h3>
	<table id="log">
		<th>Exercise</th>
		<th># Of Sets</th>
		<th># Of Repetitions</th>
		<th>Lbs.</th>
		<tr>
			<td><%= @entry.exercise %></td>
			<td><%= @entry.sets %></td>
			<td><%= @entry.reps %></td>
			<td><%= @entry.lbs %></td>
		</tr>
		<tr>
			<td><%= @entry.exercise_two %></td>
			<td><%= @entry.sets_two %></td>
			<td><%= @entry.reps_two %></td>
			<td><%= @entry.lbs_two %></td>
		</tr>
		<tr>
			<td><%= @entry.exercise_three %></td>
			<td><%= @entry.sets_three %></td>
			<td><%= @entry.reps_three %></td>
			<td><%= @entry.lbs_three %></td>
		</tr>
	</table>
	<br>
	<br>
	<p class="btn btn-success"><%= link_to "Edit Entry", edit_entry_path%></p>
	<p class="btn btn-default"><%= link_to "Go Back", entries_path%></p>
</div>