config/routes.rb
GymTime::Application.routes.draw do
  resources :exercises
  resources :users, only:[:new, :create]
  resources :workouts
  resources :authenticates, only:[:new, :create]
  delete "authenticates" => "authenticates#destroy"
  resources :entries
  get '/map' => 'home#map'
  

   root 'home#index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def map
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div id="top">
	<div id="login">
		<h1>GymTime</h1>
		<h4>Create Your Very Own Personal Workout Calendar</h4><br>
	  <%= link_to "Log In", new_authenticate_path, :class=>"btn btn-default btn-lg btn-block" %>
	  <%= link_to "Sign Up. It's Free!", new_user_path, :class=>"btn btn-default btn-lg btn-block" %>
	  <h6 style ="font-family: Arial;">(For testing, login with username = Fernando, password = fernando)</h6>
	</div>
</div>
<div id="bottom">
	<div id="wrapper">
		<div class="info">
			<h3>Schedule Workouts</h3> 
			<p><%= image_tag("cal.jpg") %></p>
		</div>
		<div class="info">
			<h3>Add/Edit Exercises</h3>
			<p><%= image_tag("exercise.jpg") %></p>
		</div>
		<div class="info">
			<h3>Create A Journal</h3>
			<p><%= image_tag("journal.jpg") %></p>
		</div>
	</div>
</div>

app/views/home/map.html.erb
<style>
  html { 
    height: 100%;
  }

  body { 
    height: 100%; 
    margin: 0; 
    padding: 0; 
    text-align: center;
  }  
</style>

<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?libraries=places&key=AIzaSyDyAnC8QYcUdwqgPP-ukX0rPIu_KlyC1KE&sensor=true"></script>

<script type="text/javascript">
var map;
var infowindow;

function initialize() {
  var mapOptions = {
    zoom: 12
  };
  map = new google.maps.Map(document.getElementById('map-canvas'),
      mapOptions);

  if(navigator.geolocation) {
    navigator.geolocation.getCurrentPosition(function(position) {
      var pos = new google.maps.LatLng(position.coords.latitude, position.coords.longitude);

      var request = {
        location: pos,
        radius: 7000,
        types: ['gym']
       };

      infowindow = new google.maps.InfoWindow();
      var service = new google.maps.places.PlacesService(map);
      service.nearbySearch(request, callback);

      map.setCenter(pos);
    }, function() {
      handleNoGeolocation(true);
    });
  } else {
    handleNoGeolocation(false);
  }
}

function callback(results, status) {
  if (status == google.maps.places.PlacesServiceStatus.OK) {
    for (var i = 0; i < results.length; i++) {
      createMarker(results[i]);
    }
  }
}

function createMarker(place) {
  var placeLoc = place.geometry.location;
  var marker = new google.maps.Marker({
    map: map,
    position: place.geometry.location
  });

  google.maps.event.addListener(marker, 'click', function() {
    infowindow.setContent(place.name);
    infowindow.open(map, this);
  });
}

function handleNoGeolocation(errorFlag) {
  if (errorFlag) {
    var content = 'Error: The Geolocation service failed.';
  } else {
    var content = 'Error: Your browser doesn\'t support geolocation.';
  }

  var options = {
    map: map,
    position: new google.maps.LatLng(60, 105),
    content: content
  };

  var infowindow = new google.maps.InfoWindow(options);
  map.setCenter(options.position);
}

google.maps.event.addDomListener(window, 'load', initialize);
</script>

<div id="map-canvas"></div>