config/routes.rb
GymTime::Application.routes.draw do
  resources :exercises
  resources :users, only:[:new, :create]
  resources :workouts
  resources :authenticates, only:[:new, :create]
  delete "authenticates" => "authenticates#destroy"
  resources :entries
  get '/map' => 'home#map'
  

   root 'home#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GymTime</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
      <div class="navbar-header">
        <p class="navbar-brand"><%= image_tag "logo.jpg" %></p>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">    
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Calendar", workouts_path %></li>
          <li><%= link_to "Journal", entries_path %></li>
          <li><%= link_to "Exercises", exercises_path %></li>
          <li><%= link_to "Gym Finder", map_path %></li>     
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown"><%=current_user ? "Logged in: #{current_user.username}" : "(not logged in)" %> <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to 'Logout', authenticates_path, {method: :delete} %></li>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <%= yield %>
</body>
</html>